import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/free-mode';
import 'swiper/css/thumbs';
import ReduxProvider from "@/redux/provider";
import Modal from "@/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ReduxProvider>
        <body className={inter.className}>
          {children}
          <div></div>
          <Modal />
        </body>
      </ReduxProvider>
    </html>
  );
}
